# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('forname', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=64)),
                ('street', models.CharField(blank=True, max_length=128, verbose_name='Ulica')),
                ('street_nr', models.CharField(blank=True, max_length=64, verbose_name='Numer domu')),
                ('city', models.CharField(blank=True, max_length=128, verbose_name='Miejscowo\u015b\u0107')),
                ('city_code', models.CharField(max_length=16, verbose_name='Kod pocztowy')),
                ('additional_info', models.TextField(blank=True, verbose_name='Dodatkowe informacje')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='bookinghouse',
            options={'verbose_name': 'Tw\xf3j obiekt', 'verbose_name_plural': 'Tw\xf3j obiekt'},
        ),
        migrations.AddField(
            model_name='bookinghouse',
            name='city_code',
            field=models.CharField(blank=True, max_length=16, verbose_name='Kod pocztowy'),
        ),
        migrations.AddField(
            model_name='bookinghouse',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
