# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20160829_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(blank=True, verbose_name='Pi\u0119tro')),
                ('size', models.CharField(blank=True, max_length=16, verbose_name='Powierzchnia pokoju')),
                ('bathroom', models.BooleanField(default=True, verbose_name='Prywatna \u0142azienka')),
                ('television', models.BooleanField(default=True, verbose_name='Telewizor')),
                ('kitchen', models.BooleanField(default=False, verbose_name='Aneks kuchenny')),
                ('internet', models.BooleanField(default=True, verbose_name='WiFi/internet')),
                ('bed', models.CharField(blank=True, max_length=64, verbose_name='\u0141\xf3\u017cka')),
                ('max_people', models.PositiveIntegerField(blank=True, verbose_name='Maksymalna ilo\u015b\u0107 os\xf3b')),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='bookingperson',
            options={'verbose_name': 'Rezerwuj\u0105cy', 'verbose_name_plural': 'Rezerwuj\u0105cy'},
        ),
        migrations.AddField(
            model_name='bookinghouse',
            name='infos',
            field=models.TextField(blank=True, verbose_name='Opis obiektu'),
        ),
        migrations.AlterField(
            model_name='bookingperson',
            name='city_code',
            field=models.CharField(blank=True, max_length=16, verbose_name='Kod pocztowy'),
        ),
        migrations.AlterField(
            model_name='bookingperson',
            name='forname',
            field=models.CharField(blank=True, max_length=32, verbose_name='Imi\u0119'),
        ),
        migrations.AlterField(
            model_name='bookingperson',
            name='last_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='Nazwisko'),
        ),
    ]
