# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 13:34
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_bookingperson_identification_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bookingperson',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='bookingperson',
            old_name='forname',
            new_name='forename',
        ),
        migrations.RenameField(
            model_name='bookingperson',
            old_name='last_name',
            new_name='surname',
        ),
        migrations.AddField(
            model_name='bookingperson',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data utworzenia'),
        ),
        migrations.AddField(
            model_name='bookingperson',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Wyznacza czy u\u017cytkownik jest aktywny. Zmie\u0144 t\u0119 warto\u015b\u0107 zamiast usuwa\u0107 u\u017cytkownika.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='bookingperson',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Wyznacza czy u\u017cytkownik mo\u017ce zalogowa\u0107 si\u0119 do strony admina.', verbose_name='staff status'),
        ),
    ]
