# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20160831_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingperson',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='bookingperson',
            name='is_confirmed',
            field=models.BooleanField(default=False, help_text='Potwierdzona rejestracja mailowa', verbose_name='Potwierdzony email'),
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='name',
            field=models.CharField(default='Pok\xf3j', max_length=64, verbose_name='Nazwa pokoju'),
        ),
        migrations.AlterField(
            model_name='bookingperson',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Wyznacza czy u\u017cytkownik jest aktywny. Zmie\u0144 t\u0119 warto\u015b\u0107 zamiast usuwa\u0107 u\u017cytkownika.', verbose_name='Aktywny'),
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Cena za jedn\u0105 dob\u0119'),
        ),
    ]
