# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='overall_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Cena za ca\u0142y pobyt'),
        ),
    ]
