# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20160831_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reservation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data dokonania rezerwacji.'),
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='level',
            field=models.PositiveIntegerField(null=True, verbose_name='Pi\u0119tro'),
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='max_people',
            field=models.PositiveIntegerField(null=True, verbose_name='Maksymalna ilo\u015b\u0107 os\xf3b'),
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='price',
            field=models.PositiveIntegerField(null=True, verbose_name='Cena za jedn\u0105 dob\u0119'),
        ),
    ]
