# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20160831_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='additional_info',
            field=models.TextField(null=True, verbose_name='Dodatkowe informacje'),
        ),
    ]
