# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_employee_housephoto_roomphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingroom',
            name='air_conditioning',
            field=models.BooleanField(default=False, verbose_name='Klimatyzacja'),
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='pets_allowed',
            field=models.BooleanField(default=False, verbose_name='Zwierz\u0119ta'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Dodatkowe informacje'),
        ),
        migrations.AlterField(
            model_name='housephoto',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_photos', to='booking.BookingHouse', verbose_name='Budynek'),
        ),
        migrations.AlterField(
            model_name='housephoto',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Zdj\u0119cie'),
        ),
        migrations.AlterField(
            model_name='roomphoto',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Zdj\u0119cie'),
        ),
        migrations.AlterField(
            model_name='roomphoto',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_photos', to='booking.BookingRoom', verbose_name='pok\xf3j'),
        ),
    ]
