# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_auto_20160912_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingroom',
            name='status',
            field=models.CharField(choices=[('Oczekuje na potwierdzenie, Nieop\u0142acony', 'wn'), ('Potwierdzona rezerwacja, Nieop\u0142acony', 'rn'), ('Oczekuje na potwierdzenie, Op\u0142acony', 'wp'), ('Potwierdzona rezerwacja, Op\u0142acony', 'rp')], default='wn', max_length=4, verbose_name='Status rezerwacji'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.BookingPerson', verbose_name='Rezerwuj\u0105cy'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.BookingRoom', verbose_name='Pok\xf3j'),
        ),
    ]
