# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_auto_20161013_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.BooleanField(default=False, verbose_name='Status p\u0142atno\u015bci'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_person', to='booking.BookingPerson', verbose_name='Rezerwuj\u0105cy'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_room', to='booking.BookingRoom', verbose_name='Pok\xf3j'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('w', 'Oczekuje na potwierdzenie'), ('r', 'Potwierdzona rezerwacja'), ('c', 'Skasowana')], default='w', max_length=4, verbose_name='Status rezerwacji'),
        ),
    ]
