# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_auto_20161013_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghouse',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, verbose_name='Numer telefonu'),
        ),
    ]
